---
- hosts: localhost
  become: yes
  gather_facts: false

  vars:
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    title: "ARTH"
    vpc_name: "ram_vpc"
    igw_name: "ram_igw"
    pubsubnet_name: "ram_pub"
    pubroute_table_name: "ram_pub_rt"
    pvtroute_table_name: "ram_pvt_rt"
    pvtsubnet_name: "ram_pvt"
    security_group_name: "ram_sg"
    vpc_cidr_block: "11.0.0.0/16"
    pubsubnet_cidr_block: "11.0.1.0/24"
    pvtsubnet_cidr_block: "11.0.2.0/24"
    destination_cidr_block: "0.0.0.0/0"
    port22_cidr_block: "0.0.0.0/0"
    region: "us-east-1"
    pubzone: "us-east-1a"
    pvtzone: "us-east-1b"
    image_id: "ami-0a699202e5027c10d"
    type: "t2.micro"
    instance_name: "ram-ec"

  tasks:
    - name: Your task name here
      # Your task details go here
